#!/bin/sh
# Install a `clipbase` launcher that does not depend on fnm.
#
# `npm link` puts the bin inside whichever fnm node version was active at the
# time, on a PATH entry fnm rebuilds per shell session. A new terminal that
# resolves a different node — Homebrew's, say — does not see it, so the command
# works in the shell that installed it and nowhere else. That is invisible until
# an agent in a fresh session reports the knowledge base as missing.
#
# This writes a launcher to ~/.local/bin, which is on PATH regardless of node,
# and pins the interpreter by trying known-good binaries in order.
#
# Usage: sh scripts/install-bin.sh   (re-run after moving the repo)

set -eu

REPO="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
ENTRY="$REPO/dist/index.js"
TARGET="${XDG_BIN_HOME:-$HOME/.local/bin}/clipbase"

[ -f "$ENTRY" ] || { echo "error: $ENTRY not found — run 'npm run build' first" >&2; exit 1; }

mkdir -p "$(dirname "$TARGET")"
cat > "$TARGET" <<EOF
#!/bin/sh
# Generated by scripts/install-bin.sh — re-run it rather than editing this.
ENTRY="$ENTRY"
for node in /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do
  [ -x "\$node" ] && exec "\$node" "\$ENTRY" "\$@"
done
exec node "\$ENTRY" "\$@"   # last resort: whatever PATH offers
EOF
chmod +x "$TARGET"

echo "installed: $TARGET -> $ENTRY"

# A second launcher for the catch-up, so running it is one word rather than a
# four-command sequence whose order matters and which nobody recalls a month
# later. A catch-up you have to look up is a catch-up that stops happening.
SYNC="$(dirname "$TARGET")/clipbase-sync"
cat > "$SYNC" <<EOF
#!/bin/sh
# Generated by scripts/install-bin.sh — re-run it rather than editing this.
# Pass --sync-only to stop after the sync, before the passes that spend.
exec sh "$REPO/scripts/weekly-sync.sh" "\$@"
EOF
chmod +x "$SYNC"
echo "installed: $SYNC -> $REPO/scripts/weekly-sync.sh"

case ":$PATH:" in
  *":$(dirname "$TARGET"):"*) ;;
  *) echo "warning: $(dirname "$TARGET") is not on your PATH" >&2 ;;
esac
